name: yl_wallet
description: yl记账 - 简单易用的记账应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/wallet.html
